### ISSUE TITLE
List films on hover

### ISSUE THREAD

**Issue by HoloPollock** [GoodbyteCo/Letterboxd-Film-Frequency#17]
List films watched that day on hover over block

**Comment by qjack001** [comment]
I think that would be too cluttered and make the tooltip too large. I would like it if clicking the square brought you to that page of your diary though

**Comment by HoloPollock** [comment]
thats pretty easy the link is letterboxed.com/{username}/films/diary/for/{year}/{month-with-zero/{date-with-zero}/

can you make the square a link though in svg

**Comment by HoloPollock** [comment]
I made the link work but I get these weird bars lol
![image](https://user-images.githubusercontent.com/24258758/124402180-6e3b5080-dce3-11eb-820e-f772048ff2f8.png)

**Comment by HoloPollock** [comment]
its the overflow scroll lol

**Comment by HoloPollock** [comment]
@qjack001 I can push my changes and you can try to fix lol
